### PR TITLE
add Instructions::StatusPacket and fix sync/bulk read mock tests

### LINKED ISSUE #28: Sync/Bulk read for devices
Popping this issue up whilst I remember. I'm happy to address it once I have a moment.

Currently devices can't properly implement the sync/bulk read protocol as each device needs to be aware of the `StatusPacket`s sent by the other devices. This is so the device can watch for the ID before it in the read and respond immediately after its been sent.

You can see this in the [mock_device](https://github.com/robohouse-delft/dynamixel2-rs/blob/eed1aa8d1ac8819e0b1b802f560ee5007757a9dd/tests/common/mock/mock_device.rs#L193) in the integration tests. The `self.device.read` call returns an `InstructionPacket` which is currently [filtered not be a `StatusPacket` ](https://github.com/robohouse-delft/dynamixel2-rs/blob/eed1aa8d1ac8819e0b1b802f560ee5007757a9dd/src/bus/packet.rs#L31)

One solution would be to add a `Instruction::StatusPacket` and parse the StatusPacket into it. 

What do you think?

### PR DESCRIPTION
**Pull request by omelia-iliffe**
closes #28 :)

### CODE REVIEW

**Comment by omelia-iliffe** [comment]
Hi @de-vri-es, have you had anytime to review this?

**Comment by de-vri-es** [comment]
Hey, sorry, I've been super busy lately. Thanks for keeping the improvements coming!

In principal this makes sense, but now the name `InstructionPacket` isn't correct anymore. With the addition of `Status`, this type can represent any known packet, not only instructions.

Problem is we're already using the name `Packet` for an unparsed packet in the read buffer.

I think we can merge this already (if CI is green), but we still need a full review of the whole library to de-duplicate, fixup names and simplify things where we can.

**Comment by omelia-iliffe** [comment]
Passing checks now. I had to add an additional timeout duration to the MockSerial integration test. 1000ms is excessive it's working so :woman_shrugging: :)

File: tests/common/mock/mock_serial_port.rs [hunk 1]
```diff
@@ -21,7 +21,7 @@ impl SharedBuffer {
 		}
 	}
 
-	pub fn read(&self) -> Option<MutexGuard<Vec<u8>>> {
+	pub fn read<'a>(&'a self) -> Option<MutexGuard<'a, Vec<u8>>> {
```
Comment (de-vri-es) [inline tests/common/mock/mock_serial_port.rs:24]:
```suggestion
	pub fn read(&self) -> Option<MutexGuard<'_, Vec<u8>>> {
```

Small note: this is the more idiomatic way to write this. But I don't mind seeing the explicit lifetimes, so let's keep them :)

**Review by de-vri-es — APPROVED** [review]

**Comment by de-vri-es** [comment]
Thanks! I'm sorry about my slow responses. Moving into my new home has turned into a multi-year project, and I'm still nowhere near done :( I appreciate you're still improving the crate!

I think now I still have one concern: we have a couple of different types to represent packets now, each slightly different for slightly different purposes, but the distinction isn't very clear. No need to do anything about it in this PR, but I want to figure out if we can reduce the number of types.

We now have `bus::{InstructionPacket, Packet, StatusPacket}`, and `device::{Instruction, Instructions}` and the individual types to represent particular payloads.

I don't have a clear idea how to approach this, though. I need to experiment a bit to see what works nice. Especially if we want it to be easy in `std` and still usable in `no-std`/`no-alloc`.

So, let's merge this to move forward, and figure out how to deal with that in a separate PR :)

**Comment by omelia-iliffe** [comment]
Thanks for merging and no worries about the slow responses. Life is busy and important. 

The improvements keep coming as I am using this with every Dynamixel project we have and we have many :) It's been a fantastic tool.

I agree re the Packet types, the library has grown considerably and it would be great to do a clean up. 
The bisync PR will move a number of types around so I will aim to get that in first and then we can have a look at tidying.
